"""
This module creates sqlalchemy classes mlbgameday data,
which is subject to the license at http://gd2.mlb.com/components/copyright.txt
"""

from sqlalchemy import Column, Date, DateTime, Float, Integer, SmallInteger, String, func, ForeignKey
from sqlalchemy.orm import backref, relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

### data model from mlbam gameday ###

class Game(Base):
    __tablename__ = 'game'
    gid = Column(String(26), primary_key = True)
    game_date = Column(Date)
    game_pk = Column(Integer)
    venue = Column(String(50))
    venue_id = Column(Integer)
    location = Column(String(20), default = '')
    datetime_local = Column(DateTime)
    datetime_et = Column(DateTime)
    first_pitch_et = Column(String(5), default = '')
    home_time = Column(String(5))
    home_time_zone = Column(String(3))
    home_ampm = Column(String(2))
    resume_home_time = Column(String(5), default = '')
    away_time = Column(String(5))
    away_time_zone = Column(String(3))
    away_ampm = Column(String(2))
    resume_away_time = Column(String(5), default = '')
    day = Column(String(3))
    game_type = Column(String(1))
    home_name_abbrev = Column(String(3))
    home_code = Column(String(3))
    home_file_code = Column(String(5))
    home_team_id = Column(Integer)
    home_team_city = Column(String(25))
    home_team_name = Column(String(30))
    home_division = Column(String(2))
    home_league_id = Column(Integer)
    home_sport_code = Column(String(3))
    home_league_id_spring = Column(String(3), default = '')
    home_split_squad = Column(String(1), default = '')
    away_name_abbrev = Column(String(3))
    away_code = Column(String(3))
    away_file_code = Column(String(5))
    away_team_id = Column(Integer)
    away_team_city = Column(String(25))
    away_team_name = Column(String(30))
    away_division = Column(String(2))
    away_league_id = Column(Integer)
    away_sport_code = Column(String(3))
    away_league_id_spring = Column(String(3), default = '')
    away_split_squad = Column(String(1), default = '')
    gameday_sw = Column(String(1))
    tiebreaker_sw = Column(String(1), default = '')
    home_games_back = Column(Float)
    away_games_back = Column(Float)
    home_games_back_wildcard = Column(Float)
    away_games_back_wildcard = Column(Float)
    home_win = Column(Integer)
    home_loss = Column(Integer)
    away_win = Column(Integer)
    away_loss = Column(Integer)
    league = Column(String(4), default = '')
    status = Column(String(15))
    ind = Column(String(2))
    home_team_runs = Column(Integer)
    away_team_runs = Column(Integer)
    home_team_hits = Column(Integer)
    away_team_hits = Column(Integer)
    home_team_errors = Column(Integer)
    away_team_errors = Column(Integer)
    reason = Column(String(17), default = '')
    description = Column(String(50), default = '')
    original_date = Column(Date)
    double_header_sw = Column(String(1), default = '')
    game_nbr = Column(Integer, default = None)
    tbd_flag = Column(String(1), default = '')
    home_team_hr = Column(Integer, default = None)
    away_team_hr = Column(Integer, default = None)
    home_team_sb = Column(Integer, default = None)
    away_team_sb = Column(Integer, default = None)
    home_team_so = Column(Integer, default = None)
    away_team_so = Column(Integer, default = None)
    resume_date = Column(Date, default = None)
    resume_time_date = Column(DateTime, default = None)
    resume_ampm = Column(String(2), default = '')
    resume_home_ampm = Column(String(2), default = '')
    series = Column(String(12), default = '')
    series_num = Column(Integer, default = None)
    ser_home_nbr = Column(Integer, default = None)
    ser_games = Column(Integer, default = None)
    scheduled_innings = Column(Integer)
    if_necessary = Column(String(1), default = '')
    tv_station = Column(String(60))

    def __repr__(self):
        return '<Game(gid = %s, game_pk = %i, home = %s, away = %s, venue = %s)>' % \
                (self.gid, self.game_pk, str(self.home_team_runs), str(self.away_team_runs), self.venue)

class Player(Base):
    __tablename__ = 'player'
    gid = Column(String(26), primary_key = True)
    player_id = Column(Integer, primary_key = True)
    home_flag = Column(Integer, primary_key = True)
    game_date = Column(DateTime)
    game_pk = Column(Integer)
    first = Column(String(12))
    last = Column(String(15))
    boxname = Column(String(15))
    position = Column(String(2))
    team_id = Column(Integer, default = None)
    team_abbrev = Column(String(3))
    parent_team_id = Column(Integer)
    parent_team_abbrev = Column(String(3))
    num = Column(Integer)
    bats = Column(String(1))
    rl = Column(String(1))
    game_position = Column(String(2), default = '')
    current_position = Column(String(2), default = '')
    bat_order = Column(Integer, default = None)
    status = Column(String(1))
    avg = Column(Float)
    hr = Column(Integer)
    rbi = Column(Integer)
    wins = Column(Integer, default = None)
    losses = Column(Integer, default = None)
    era = Column(Float, default = None)

    def __repr__(self):
        return '<Player(gid = %s, game_pk = %i, player_id = %i boxname = %s)>' % \
        (self.gid, self.game_pk, self.player_id, self.boxname)

class Coach(Base):
    __tablename__ = 'coach'
    gid = Column(String(26), primary_key = True)
    coach_id = Column(Integer, primary_key = True)
    home_flag = Column(Integer, primary_key = True)
    game_date = Column(DateTime)
    game_pk = Column(Integer)
    first = Column(String(10))
    last = Column(String(15))
    num = Column(Integer)
    position = Column(String(25))

    def __repr__(self):
        return '<Coach(gid = %s, last = %s)>' % (self.gid, self.last)

class Umpire(Base):
    __tablename__ = 'umpire'
    gid = Column(String(26), primary_key = True)
    umpire_id = Column(Integer, primary_key = True)
    position = Column(String(6), primary_key = True)
    game_pk = Column(Integer)
    game_date = Column(DateTime)
    last = Column(String(15), default = '')
    first = Column(String(10), default = '')
    name = Column(String(25))

    def __repr__(self):
        return '<Umpire(gid = %s, last = %s)>' % (self.gid, self.last)

class HIP(Base):
    __tablename__ = 'hip'
    gid = Column(String(26), primary_key = True)
    pitcher = Column(Integer, primary_key = True)
    batter = Column(Integer, primary_key = True)
    venue_id = Column(Integer)
    game_pk = Column(Integer)
    des = Column(String(20))
    x = Column(Float)
    y = Column(Float)
    hip_type = Column(Float)
    team = Column(String(1))
    inning = Column(Integer)

    def __repr__(self):
        return '<HIP(gid = %s, inning = %s, des = %s)>' \
               % (self.gid, self.inning, self.des)

class AtBat(Base):
    __tablename__ = 'atbat'
    gid = Column(String(26), primary_key = True)
    game_event_number = Column(Integer, primary_key = True)
    game_pk = Column(Integer)
    venue_id = Column(Integer)
    event_num = Column(Integer)
    inning = Column(Integer)
    inning_topbot = Column(String(3))
    play_guid = Column(String(36), default = '')
    pitcher = Column(Integer)
    catcher = Column(Integer)
    batter = Column(Integer)
    umpire = Column(Integer)
    start_outs = Column(Integer)
    start_base_state = Column(String(3))
    start_out_base_state = Column(String(4))
    start_home_team_runs = Column(Integer)
    start_away_team_runs = Column(Integer)
    start_1B = Column(Integer)
    start_2B = Column(Integer)
    start_3B = Column(Integer)
    b = Column(Integer)
    s = Column(Integer)
    o = Column(Integer)
    num = Column(Integer, default = None)
    p_throws = Column(String(1), default = '')
    stand = Column(String(1), default = '')
    b_height = Column(String(4), default = '')
    score = Column(String(1), default = '')
    start_tfs = Column(String(6), default = '')
    start_tfs_zulu = Column(String(20), default = '')
    des = Column(String(425))
    des_es = Column(String(400))
    event = Column(String(25))
    event_es = Column(String(50), default = '')
    event2 = Column(String(25), default = '')
    event2_es = Column(String(50), default = '')
    event3 = Column(String(25), default = '')
    event3_es = Column(String(50), default = '')
    event4 = Column(String(25), default = '')
    event4_es = Column(String(50), default = '')
    end_outs = Column(Integer)
    end_base_state = Column(String(3))
    end_out_base_state = Column(String(4))
    end_home_team_runs = Column(Integer)
    end_away_team_runs = Column(Integer)
    end_1B = Column(Integer)
    end_2B = Column(Integer)
    end_3B = Column(Integer)

    def __repr__(self):
        return '<Event(gid = %s, game_event_number = %i, inning = %i, event_type = %s)>' \
               % (self.gid, self.game_event_number, self.inning, self.event_type)

class Action(Base):
    __tablename__ = 'action'
    gid = Column(String(26), primary_key = True)
    game_event_number = Column(Integer, primary_key = True)
    game_pk = Column(Integer)
    venue_id = Column(Integer)
    event_num = Column(Integer)
    inning = Column(Integer)
    inning_topbot = Column(String(3))
    play_guid = Column(String(36), default = '')
    pitcher = Column(Integer)
    catcher = Column(Integer)
    batter = Column(Integer)
    umpire = Column(Integer)
    player = Column(Integer, default = None)
    start_outs = Column(Integer)
    start_base_state = Column(String(3))
    start_out_base_state = Column(String(4))
    start_home_team_runs = Column(Integer)
    start_away_team_runs = Column(Integer)
    start_1B = Column(Integer)
    start_2B = Column(Integer)
    start_3B = Column(Integer)
    b = Column(Integer)
    s = Column(Integer)
    o = Column(Integer)
    home_team_runs = Column(Integer, default = None)
    away_team_runs = Column(Integer, default = None)
    pitch = Column(Integer, default = None)
    score = Column(String(1), default = '')
    tfs = Column(String(6), default = '')
    tfs_zulu = Column(String(20), default = '')
    des = Column(String(425))
    des_es = Column(String(400))
    event = Column(String(25))
    event_es = Column(String(50), default = '')
    event2 = Column(String(25), default = '')
    event2_es = Column(String(50), default = '')
    event3 = Column(String(25), default = '')
    event3_es = Column(String(50), default = '')
    event4 = Column(String(25), default = '')
    event4_es = Column(String(50), default = '')
    end_outs = Column(Integer)
    end_base_state = Column(String(3))
    end_out_base_state = Column(String(4))
    end_home_team_runs = Column(Integer)
    end_away_team_runs = Column(Integer)
    end_1B = Column(Integer)
    end_2B = Column(Integer)
    end_3B = Column(Integer)

    def __repr__(self):
        return '<Event(gid = %s, game_event_number = %i, inning = %i, event_type = %s)>' \
               % (self.gid, self.game_event_number, self.inning, self.event_type)

class Pitch(Base):
    __tablename__ = 'pitch'
    gid = Column(String(26), primary_key = True)
    game_pitch_count = Column(Integer, primary_key = True)
    game_pk = Column(Integer)
    pitch_id = Column(Integer)
    venue_id = Column(Integer)
    inning = Column(Integer)
    inning_topbot = Column(String(3))
    game_event_number = Column(Integer)
    event_num = Column(Integer)
    event = Column(String(35))
    pitcher = Column(Integer)
    catcher = Column(Integer)
    batter = Column(Integer)
    umpire = Column(Integer)
    start_outs = Column(Integer)
    start_base_state = Column(String(3))
    start_out_base_state = Column(String(4))
    start_home_team_runs = Column(Integer)
    start_away_team_runs = Column(Integer)
    start_1B = Column(Integer)
    start_2B = Column(Integer)
    start_3B = Column(Integer)
    des = Column(String(35))
    des_es = Column(String(35))
    p_type = Column(String(1))
    tfs = Column(String(6))
    tfs_zulu = Column(String(20))
    x = Column(Float)
    y = Column(Float)
    sv_id = Column(DateTime)
    play_guid = Column(String(36))
    start_speed = Column(Float)
    end_speed = Column(Float)
    sz_top = Column(Float)
    sz_bot = Column(Float)
    pfx_x = Column(Float)
    pfx_z = Column(Float)
    px = Column(Float)
    pz = Column(Float)
    x0 = Column(Float)
    y0 = Column(Float)
    z0 = Column(Float)
    vx0 = Column(Float)
    vy0 = Column(Float)
    vz0 = Column(Float)
    ax = Column(Float)
    ay = Column(Float)
    az = Column(Float)
    break_y = Column(Float)
    break_angle = Column(Float)
    break_length = Column(Float)
    pitch_type = Column(String(2))
    type_confidence = Column(Float)
    zone = Column(Integer)
    nasty = Column(Integer)
    spin_dir = Column(Float)
    spin_rate = Column(Float)
    cc = Column(String(200))
    mt = Column(String(1))
    on_1b = Column(Integer, default = None)
    on_2b = Column(Integer, default = None)
    on_3b = Column(Integer, default = None)
    end_outs = Column(Integer)
    end_base_state = Column(String(3))
    end_out_base_state = Column(String(4))
    end_home_team_runs = Column(Integer)
    end_away_team_runs = Column(Integer)
    end_1B = Column(Integer)
    end_2B = Column(Integer)
    end_3B = Column(Integer)

    def __repr__(self):
        return '<Pitch(gid = %s, pitch_num = %i, pitch_type = %s)>' % \
               (self.gid, self.pitch_num, self.pitch_type)


class Runner(Base):
    __tablename__ = 'runner'
    gid = Column(String(26), primary_key = True)
    game_runner_count = Column(Integer, primary_key = True)
    game_pk = Column(Integer)
    runner_id = Column(Integer)
    game_event_number = Column(Integer)
    venue_id = Column(Integer)
    event_num = Column(Integer, default = None)
    inning = Column(Integer)
    inning_topbot = Column(String(3))
    pitcher = Column(Integer)
    catcher = Column(Integer)
    batter = Column(Integer)
    umpire = Column(Integer)
    start_outs = Column(Integer)
    start_base_state = Column(String(3))
    start_out_base_state = Column(String(4))
    start_home_team_runs = Column(Integer)
    start_away_team_runs = Column(Integer)
    start_1B = Column(Integer)
    start_2B = Column(Integer)
    start_3B = Column(Integer)
    event = Column(String(25))
    start = Column(String(2))
    end = Column(String(2))
    score = Column(String(1), default = '')
    rbi = Column(String(1), default = '')
    earned = Column(String(1), default = '')
    end_outs = Column(Integer)
    end_base_state = Column(String(3))
    end_out_base_state = Column(String(4))
    end_home_team_runs = Column(Integer)
    end_away_team_runs = Column(Integer)
    end_1B = Column(Integer)
    end_2B = Column(Integer)
    end_3B = Column(Integer)

    def __repr__(self):
        return '<Runner(game_pk = %s, gid = %s, des = %s)>' % \
               (str(self.game_pk), str(self.event_num), str(self.des))

class Pickoff(Base):
    __tablename__ = 'pickoff'
    gid = Column(String(26), primary_key = True)
    game_pickofff_count = Column(Integer, primary_key = True)
    game_pk = Column(Integer)
    game_event_number = Column(Integer)
    venue_id = Column(Integer)
    event_num = Column(Integer, default = None)
    inning = Column(Integer)
    inning_topbot = Column(String(3))
    pitcher = Column(Integer)
    catcher = Column(Integer)
    batter = Column(Integer)
    umpire = Column(Integer)
    start_outs = Column(Integer)
    start_base_state = Column(String(3))
    start_out_base_state = Column(String(4))
    start_home_team_runs = Column(Integer)
    start_away_team_runs = Column(Integer)
    start_1B = Column(Integer)
    start_2B = Column(Integer)
    start_3B = Column(Integer)
    des = Column(String(20))
    des_es = Column(String(20), default = '')
    play_guid = Column(String(36), default = '')
    end_outs = Column(Integer)
    end_base_state = Column(String(3))
    end_out_base_state = Column(String(4))
    end_home_team_runs = Column(Integer)
    end_away_team_runs = Column(Integer)
    end_1B = Column(Integer)
    end_2B = Column(Integer)
    end_3B = Column(Integer)

    def __repr__(self):
        return '<Pickoff(gid = %s, game_event_number = %i, atbat_pickoff_number = %s)>' \
               % (self.gid, self.game_event_number, self.atbat_pickoff_numbers)


### data model from baseball savant trajectory csv downloads ###

class Trajectory(Base):
    __tablename__ = 'trajectory'
    game_pk = Column(Integer, primary_key = True)
    pitch_id = Column(Integer, primary_key = True)
    pitch_type = Column(String(2))
    game_date = Column(DateTime)
    start_speed = Column(Float)
    x0 = Column(Float)
    z0 = Column(Float)
    player_name = Column(String(30))
    batter = Column(Integer)
    pitcher = Column(Integer)
    events = Column(String(10))
    description = Column(String(20))
    spin_dir = Column(Float)
    spin_rate = Column(Float)
    break_angle = Column(Float)
    break_length = Column(Float)
    zone = Column(Integer)
    des = Column(String(100))
    game_type = Column(String(1))
    stand = Column(String(1))
    p_throws = Column(String(1))
    home_team = Column(String(3))
    away_team = Column(String(3))
    event_type = Column(String(1))
    hit_location = Column(Integer)
    bb_type = Column(Integer)
    balls = Column(Integer)
    strikes = Column(Integer)
    game_year = Column(Integer)
    pfx_x = Column(Float)
    pfx_z = Column(Float)
    px = Column(Float)
    pz = Column(Float)
    on_3b = Column(Integer)
    on_2b = Column(Integer)
    on_1b = Column(Integer)
    outs_when_up = Column(Integer)
    inning = Column(Integer)
    inning_topbot = Column(String(3))
    hc_x = Column(Float)
    hc_y = Column(Float)
    tfs = Column(Integer)
    tfs_zulu = Column(DateTime)
    catcher = Column(Integer)
    umpire = Column(Integer)
    sv_id = Column(String(13))
    vx0 = Column(Float)
    vy0 = Column(Float)
    vz0 = Column(Float)
    ax = Column(Float)
    ay = Column(Float)
    az = Column(Float)
    sz_top = Column(Float)
    sz_bot = Column(Float)
    hit_distance_sc = Column(Float)
    hit_speed = Column(Float)
    hit_angle = Column(Float)
    effective_speed = Column(Float)
    release_spin_rate = Column(Float)
    release_extension = Column(Float)

    def __repr__(self):
        return '<Trajectory(game_pk = %i, pitcher = %s, game_date = %s)>' % \
               (self.game_pk, self.player_name, self.game_date.srftime('%Y-%m-%d'))


### data model from retrosheet ###

class Event(Base):
    __tablename__ = 'event'
    game_id = Column(String(12), primary_key = True)
    event_id = Column(Integer, primary_key = True)
    away_team_id = Column(String(3))
    inn_ct = Column(Integer)
    bat_home_id = Column(Integer)
    outs_ct = Column(Integer)
    balls_ct = Column(Integer)
    strikes_ct = Column(Integer)
    pitch_seq_tx = Column(String(40))
    away_score_ct = Column(Integer)
    home_score_ct = Column(Integer)
    bat_id = Column(String(8))
    bat_hand_cd = Column(String(1))
    resp_bat_id = Column(String(8))
    bat_on_deck_id = Column(String(8))
    bat_in_hold_id = Column(String(8))
    resp_bat_hand_cd = Column(String(1))
    pit_id = Column(String(8))
    pit_hand_cd = Column(String(1))
    resp_pit_id = Column(String(8))
    resp_pit_hand_cd = Column(String(1))
    pos2_fld_id = Column(String(8))
    pos3_fld_id = Column(String(8))
    pos4_fld_id = Column(String(8))
    pos5_fld_id = Column(String(8))
    pos6_fld_id = Column(String(8))
    pos7_fld_id = Column(String(8))
    pos8_fld_id = Column(String(8))
    pos9_fld_id = Column(String(8))
    base1_run_id = Column(String(8))
    base2_run_id = Column(String(8))
    base3_run_id = Column(String(8))
    event_tx = Column(String(100))
    leadoff_fl = Column(String(1))
    ph_fl = Column(String(1))
    bat_fld_cd = Column(Integer)
    bat_lineup_id = Column(Integer)
    event_cd = Column(Integer)
    bat_event_fl = Column(String(1))
    ab_fl = Column(String(1))
    h_cd = Column(Integer)
    sh_fl = Column(String(1))
    sf_fl = Column(String(1))
    event_outs_ct = Column(Integer)
    dp_fl = Column(String(1))
    tp_fl = Column(String(1))
    rbi_ct = Column(Integer)
    wp_fl = Column(String(1))
    pb_fl = Column(String(1))
    fld_cd = Column(Integer)
    battedball_cd = Column(String(1))
    bunt_fl = Column(String(1))
    foul_fl = Column(String(1))
    battedball_loc_tx = Column(String(5))
    err_ct = Column(Integer)
    err1_fld_cd = Column(Integer)
    err1_cd = Column(String(1))
    err2_fld_cd = Column(Integer)
    err2_cd = Column(String(1))
    err3_fld_cd = Column(Integer)
    err3_cd = Column(String(1))
    bat_dest_id = Column(Integer)
    run1_dest_id = Column(Integer)
    run2_dest_id = Column(Integer)
    run3_dest_id = Column(Integer)
    bat_play_tx = Column(String(8))
    run1_play_tx = Column(String(15))
    run2_play_tx = Column(String(15))
    run3_play_tx = Column(String(15))
    run1_sb_fl = Column(String(1))
    run2_sb_fl = Column(String(1))
    run3_sb_fl = Column(String(1))
    run1_cs_fl = Column(String(1))
    run2_cs_fl = Column(String(1))
    run3_cs_fl = Column(String(1))
    run1_pk_fl = Column(String(1))
    run2_pk_fl = Column(String(1))
    run3_pk_fl = Column(String(1))
    run1_resp_pit_id = Column(String(8))
    run2_resp_pit_id = Column(String(8))
    run3_resp_pit_id = Column(String(8))
    game_new_fl = Column(String(1))
    game_end_fl = Column(String(1))
    pr_run1_fl = Column(String(1))
    pr_run2_fl = Column(String(1))
    pr_run3_fl = Column(String(1))
    removed_for_pr_run1_id = Column(String(8))
    removed_for_pr_run2_id = Column(String(8))
    removed_for_pr_run3_id = Column(String(8))
    removed_for_ph_bat_id = Column(String(8))
    removed_for_ph_bat_fld_cd = Column(Integer)
    po1_fld_cd = Column(Integer)
    po2_fld_cd = Column(Integer)
    po3_fld_cd = Column(Integer)
    ass1_fld_cd = Column(Integer)
    ass2_fld_cd = Column(Integer)
    ass3_fld_cd = Column(Integer)
    ass4_fld_cd = Column(Integer)
    ass5_fld_cd = Column(Integer)
    ### extended fields ###
    home_team_id = Column(String(3))
    bat_team_id = Column(String(3))
    fld_team_id = Column(String(3))
    bat_last_id = Column(Integer)
    inn_new_fl = Column(String(1))
    inn_end_fl = Column(String(1))
    start_bat_score_ct = Column(Integer)
    start_fld_score_ct = Column(Integer)
    inn_runs_ct = Column(Integer)
    game_pa_ct = Column(Integer)
    inn_pa_ct = Column(Integer)
    pa_new_fl = Column(String(1))
    pa_trunc_fl = Column(String(1))
    start_bases_cd = Column(Integer)
    end_bases_cd = Column(Integer)
    bat_start_fl = Column(String(1))
    resp_bat_start_fl = Column(String(1))
    pit_start_fl = Column(String(1))
    resp_pit_start_fl = Column(String(1))
    run1_fld_cd = Column(Integer)
    run1_lineup_cd = Column(Integer)
    run1_origin_event_id = Column(Integer)
    run2_fld_cd = Column(Integer)
    run2_lineup_cd = Column(Integer)
    run2_origin_event_id = Column(Integer)
    run3_fld_cd = Column(Integer)
    run3_lineup_cd = Column(Integer)
    run3_origin_event_id = Column(Integer)
    run1_resp_cat_id = Column(String(8))
    run2_resp_cat_id = Column(String(8))
    run3_resp_cat_id = Column(String(8))
    pa_ball_ct = Column(Integer)
    pa_called_ball_ct = Column(Integer, default = 0)
    pa_intent_ball_ct = Column(Integer)
    pa_pitchout_ball_ct = Column(Integer)
    pa_hitbatter_ball_ct = Column(Integer)
    pa_other_ball_ct = Column(Integer)
    pa_strike_ct = Column(Integer)
    pa_called_strike_ct = Column(Integer)
    pa_swingmiss_strike_ct = Column(Integer)
    pa_foul_strike_ct = Column(Integer)
    pa_inplay_strike_ct = Column(Integer)
    pa_other_strike_ct = Column(Integer)
    event_runs_ct = Column(Integer)
    fld_id = Column(String(8))
    base2_force_fl = Column(String(1))
    base3_force_fl = Column(String(1))
    base4_force_fl = Column(String(1))
    bat_safe_err_fl = Column(String(1))
    bat_fate_id = Column(Integer)
    run1_fate_id = Column(Integer)
    run2_fate_id = Column(Integer)
    run3_fate_id = Column(Integer)
    fate_runs_ct = Column(Integer)
    ass6_fld_cd = Column(Integer)
    ass7_fld_cd = Column(Integer)
    ass8_fld_cd = Column(Integer)
    ass9_fld_cd = Column(Integer)
    ass10_fld_cd = Column(Integer)
    unknown_out_exc_fl = Column(String(1))
    uncertain_play_exc_fl = Column(String(1))

    def __repr__(self):
        return '<Event(game_id = %s, event_id = %i, inning = %i)>' % \
                (self.game_id, self.event_id, self.inn_ct)

class GameLog(Base):
    __tablename__ = 'game_log'
    game_id = Column(String(12), primary_key = True)
    game_datetime = Column(DateTime)
    game_dt = Column(String(6))
    game_ct = Column(Integer)
    game_dy = Column(String(9))
    start_game_tm = Column(String(4))
    dh_fl = Column(String(1))
    daynight_park_cd = Column(String(1))
    away_team_id = Column(String(3))
    home_team_id = Column(String(3))
    away_start_pit_id = Column(String(8))
    home_start_pit_id = Column(String(8))
    base4_ump_id = Column(String(8), default = '')
    base1_ump_id = Column(String(8), default = '')
    base2_ump_id = Column(String(8), default = '')
    base3_ump_id = Column(String(8), default = '')
    lf_ump_id = Column(String(8), default = '')
    rf_ump_id = Column(String(8), default = '')
    attend_park_ct = Column(Integer)
    scorer_record_id = Column(Integer)
    translator_record_id = Column(String(50))
    inputter_record_id = Column(String(50))
    input_record_ts = Column(String(18))
    edit_record_ts = Column(String(18))
    method_record_cd = Column(Integer)
    pitches_record_cd = Column(Integer)
    temp_park_ct = Column(Integer)
    wind_direction_park_cd = Column(Integer)
    wind_speed_park_ct = Column(Integer)
    field_park_cd = Column(Integer)
    precip_park_cd = Column(Integer)
    sky_park_cd = Column(Integer)
    minutes_game_ct = Column(Integer)
    inn_ct = Column(Integer)
    away_score_ct = Column(Integer)
    home_score_ct = Column(Integer)
    away_hits_ct = Column(Integer)
    home_hits_ct = Column(Integer)
    away_err_ct = Column(Integer)
    home_err_ct = Column(Integer)
    away_lob_ct = Column(Integer)
    home_lob_ct = Column(Integer)
    win_pit_id = Column(String(8))
    lose_pit_id = Column(String(8))
    save_pit_id = Column(String(8), default = '')
    gwrbi_bat_id = Column(String(8), default = '')
    away_lineup1_bat_id = Column(String(8))
    away_lineup1_fld_cd = Column(Integer)
    away_lineup2_bat_id = Column(String(8))
    away_lineup2_fld_cd = Column(Integer)
    away_lineup3_bat_id = Column(String(8))
    away_lineup3_fld_cd = Column(Integer)
    away_lineup4_bat_id = Column(String(8))
    away_lineup4_fld_cd = Column(Integer)
    away_lineup5_bat_id = Column(String(8))
    away_lineup5_fld_cd = Column(Integer)
    away_lineup6_bat_id = Column(String(8))
    away_lineup6_fld_cd = Column(Integer)
    away_lineup7_bat_id = Column(String(8))
    away_lineup7_fld_cd = Column(Integer)
    away_lineup8_bat_id = Column(String(8))
    away_lineup8_fld_cd = Column(Integer)
    away_lineup9_bat_id = Column(String(8))
    away_lineup9_fld_cd = Column(Integer)
    home_lineup1_bat_id = Column(String(8))
    home_lineup1_fld_cd = Column(Integer)
    home_lineup2_bat_id = Column(String(8))
    home_lineup2_fld_cd = Column(Integer)
    home_lineup3_bat_id = Column(String(8))
    home_lineup3_fld_cd = Column(Integer)
    home_lineup4_bat_id = Column(String(8))
    home_lineup4_fld_cd = Column(Integer)
    home_lineup5_bat_id = Column(String(8))
    home_lineup5_fld_cd = Column(Integer)
    home_lineup6_bat_id = Column(String(8))
    home_lineup6_fld_cd = Column(Integer)
    home_lineup7_bat_id = Column(String(8))
    home_lineup7_fld_cd = Column(Integer)
    home_lineup8_bat_id = Column(String(8))
    home_lineup8_fld_cd = Column(Integer)
    home_lineup9_bat_id = Column(String(8), default = '')
    home_lineup9_fld_cd = Column(Integer)
    away_finish_pit_id = Column(String(8), default = '')
    home_finish_pit_id = Column(Integer)

    def __repr__(self):
        return '<GameLog(game_id = %s, away_score_ct = %i, home_score_ct = %i)>' % \
        (self.game_id, self.away_score_ct, self.Home_score_ct)

class Sub(Base):
    __tablename__ = 'sub'
    game_id = Column(String(12), primary_key = True)
    sub_id = Column(String(8), primary_key = True)
    sub_fld_cd = Column(Integer, primary_key = True)
    event_id = Column(Integer, primary_key = True)
    inn_ct = Column(Integer)
    bat_home_id = Column(Integer)
    sub_home_id = Column(Integer)
    sub_lineup_id = Column(Integer)
    removed_id = Column(String(8), primary_key = True)
    removed_fld_cd = Column(Integer)

    def __repr__(self):
        return '<Sub(game_id = %s, event_id = %i, inning = %i, remove = %s)>' % \
        (self.game_id, self.event_id, self.inn_ct, self.removed_id)


def create_db(engine):
    Base.metadata.create_all(bind = engine)
